### All recipes - index

GET http://localhost:3000/products

### index with params

GET http://localhost:3000/products?discount=true

### another index with params

GET http://localhost:3000/products?search=liver

###

GET http://localhost:3000/products?sort=price&sort_order=desc



### 1 recipe

GET http://localhost:3000/products/8

### Create action

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": " ",
  "description": "yessir",
  "price": 10,
  "quantity": "yellow"
}

### Update action

PATCH http://localhost:3000/products/8
Content-Type: application/json

{
  "quantity": 9,
  "image_url": "https://previews.123rf.com/images/lineartestpilot/lineartestpilot1802/lineartestpilot180281961/95638653-cartoon-eyeball-laughing.jpg" 
}

### Delete action

DELETE http://localhost:3000/products/7


### SUPPLIERS

GET http://localhost:3000/suppliers

###

POST http://localhost:3000/suppliers
Content-Type: application/json

{
  "name": "Fake supplier . org",
  "email": "lol",
  "phone_number": "none of ur business, get it?"
}

###

PATCH http://localhost:3000/suppliers/3
Content-Type: application/json

{
  "email": "wouldn't you like to know."
}

###

DELETE http://localhost:3000/suppliers/4

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "testing tester number 2",
  "email": "test2@test.com",
  "password": "password",
  "password_confirmation": "password"
}