### All recipes - index

GET http://localhost:3000/products

### 1 recipe

GET http://localhost:3000/products/8

### Create action

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "useless organs",
  "price": "6",
  "description": "I just really don't wanna waste them" 
}

### Update action

PATCH http://localhost:3000/products/2
Content-Type: application/json

{
  "image_url": "https://cdn.vox-cdn.com/thumbor/hRa88_G-3n0J7ivEG65WYcjfPeo=/46x0:1054x672/1400x1050/filters:focal(46x0:1054x672):format(jpeg)/cdn.vox-cdn.com/assets/2368289/heart_shutterstock.jpg"
}

### Delete action

DELETE http://localhost:3000/products/7