### All recipes - index

GET http://localhost:3000/products

### 1 recipe

GET http://localhost:3000/products/8

### Create action

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": " ",
  "description": "yessir",
  "price": 10,
  "quantity": "yellow"
}

### Update action

PATCH http://localhost:3000/products/8
Content-Type: application/json

{
  "quantity": 9,
  "image_url": "https://previews.123rf.com/images/lineartestpilot/lineartestpilot1802/lineartestpilot180281961/95638653-cartoon-eyeball-laughing.jpg" 
}

### Delete action

DELETE http://localhost:3000/products/7